name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: publish
      uses: brandedoutcast/publish-nuget@v2.5.2
      with: 
        PROJECT_FILE_PATH: SqlRunner/SqlRunner.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
